### ISSUE TITLE
bundle 地址是 https 的话就会报错

### ISSUE THREAD

**Issue by yesmeck** [SaitoWu/linner#44]
比如这个：https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.6.4/semantic.css

```
/Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify f
ailed (OpenSSL::SSL::SSLError)
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:318:in `open_http'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:736:in `buffer_open'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:211:in `block in open_loop'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:209:in `catch'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:209:in `open_loop'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:716:in `open'
        from /Users/meck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:34:in `open'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/bundler.rb:61:in `block in install_to_repository'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/bundler.rb:59:in `open'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/bundler.rb:59:in `install_to_repository'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/bundler.rb:43:in `block in install'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/bundler.rb:38:in `each'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/bundler.rb:38:in `install'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/bundler.rb:53:in `perform'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/lib/linner/command.rb:53:in `watch'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /Users/meck/.rvm/gems/ruby-2.2.0/gems/linner-0.8.3/bin/linner:11:in `<top (required)>'
        from /Users/meck/.rvm/gems/ruby-2.2.0/bin/linner:23:in `load'
        from /Users/meck/.rvm/gems/ruby-2.2.0/bin/linner:23:in `<main>'
        from /Users/meck/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
        from /Users/meck/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by SaitoWu** [comment]
这个 URL 的链接没有经过 SSL 认证, 导致 Ruby 出问题.

正确的 SSL 认证的 https 地址. 例如: https://raw.githubusercontent.com/SaitoWu/linner/master/vendor/livereload.js 是没问题的.

**Comment by yesmeck** [comment]
确实，换成 http 就 ok 了。
